# -*- coding: utf-8 -*-
"""channel estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0Pdt2PgZVlLiBS4zdmZqPtXASU1nQAD
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec


#  1. GOLAY PAIR GENERATOR  (self-contained)


def golay_pair(n):
    """
    Recursive Golay-Rudin-Shapiro construction.
    Returns sequences a, b of length 2^n with values in {+1, -1}.
    """
    if n == 0:
        return np.array([1.0]), np.array([1.0])
    a_prev, b_prev = golay_pair(n - 1)
    return (np.concatenate([a_prev,  b_prev]),
            np.concatenate([a_prev, -b_prev]))


#  2. MULTIPATH CHANNEL SIMULATOR


def make_channel(num_taps=5, seed=42):
    """
    Create a random multipath channel with `num_taps` complex taps.
    Tap gains are complex Gaussian; power decays exponentially with delay.
    Returns h of shape (num_taps,).
    """
    rng = np.random.default_rng(seed)
    decay   = np.exp(-0.4 * np.arange(num_taps))          # exponential power decay
    gains   = (rng.standard_normal(num_taps) +
               1j * rng.standard_normal(num_taps)) / np.sqrt(2)
    h       = gains * decay
    h      /= np.linalg.norm(h)                            # normalise to unit energy
    return h


def transmit(sequence, h, snr_db):
    """
    Pass `sequence` through channel h and add AWGN.
    y = conv(sequence, h) + noise
    Returns the received signal (same length as sequence, linear convolution).
    """
    y_clean  = np.convolve(sequence, h)                    # full linear convolution
    sig_pow  = np.mean(np.abs(y_clean) ** 2)
    snr_lin  = 10 ** (snr_db / 10)
    noise_std = np.sqrt(sig_pow / (2 * snr_lin))
    rng = np.random.default_rng()
    noise = (rng.standard_normal(len(y_clean)) +
             1j * rng.standard_normal(len(y_clean))) * noise_std
    return y_clean + noise



#  3. GOLAY-BASED CHANNEL ESTIMATOR


def estimate_channel_golay(y_a, y_b, a, b, num_taps):
    """
    Estimate channel impulse response using Golay complementary property.

    Formula (frequency domain):
        H_est(f) = ( Y_a(f)·conj(A(f))  +  Y_b(f)·conj(B(f)) ) / 2N

    Because |A(f)|² + |B(f)|² = 2N for all f, this is the optimal
    (zero-forcing) estimator with flat noise enhancement across all frequencies.

    Parameters
    ----------
    y_a, y_b  : received signals after transmitting a and b respectively
    a,  b     : the original Golay sequences
    num_taps  : number of channel taps to return (truncate IFFT output)

    Returns
    -------
    h_est : estimated channel impulse response (length = num_taps)
    """
    N    = len(a)
    Nfft = len(y_a)                   # FFT size = length of received signal

    Y_a  = np.fft.fft(y_a, Nfft)
    Y_b  = np.fft.fft(y_b, Nfft)
    A    = np.fft.fft(a,   Nfft)
    B    = np.fft.fft(b,   Nfft)

    H_est = (Y_a * np.conj(A) + Y_b * np.conj(B)) / (2 * N)
    h_est = np.fft.ifft(H_est).real   # channel is real-valued here

    return h_est[:num_taps]           # keep only the first num_taps samples



#  4. LEAST-SQUARES BASELINE (random pilots)

def estimate_channel_ls(y, pilot, num_taps):
    """
    Least-Squares channel estimator using a single random pilot sequence.

    Formula:
        H_est(f) = Y(f) / X(f)

    Division by X(f) can amplify noise at frequencies where |X(f)| is small
    (spectral nulls) — a fundamental weakness of random pilot sequences.
    """
    Nfft  = len(y)
    Y     = np.fft.fft(y,     Nfft)
    X     = np.fft.fft(pilot, Nfft)

    # Avoid division by very small values (regularisation)
    eps   = 1e-6 * np.max(np.abs(X))
    H_est = Y / (X + eps * np.sign(X + eps))
    h_est = np.fft.ifft(H_est).real

    return h_est[:num_taps]



#  5. MSE vs SNR EXPERIMENT


def mse_vs_snr(n=5, num_taps=5, snr_range_db=None, num_trials=200):
    """
    Run channel estimation at each SNR level and record MSE.

    Returns
    -------
    snr_range  : array of SNR values in dB
    mse_golay  : MSE of Golay estimator at each SNR
    mse_ls     : MSE of LS (random pilot) estimator at each SNR
    h_true     : the true channel used (for plotting)
    """
    if snr_range_db is None:
        snr_range_db = np.arange(0, 31, 2)   # 0 to 30 dB in steps of 2

    a, b   = golay_pair(n)
    h_true = make_channel(num_taps=num_taps, seed=7)
    N      = len(a)

    mse_golay = np.zeros(len(snr_range_db))
    mse_ls    = np.zeros(len(snr_range_db))

    rng_pilot = np.random.default_rng(seed=99)

    for i, snr_db in enumerate(snr_range_db):
        err_golay_list = []
        err_ls_list    = []

        for _ in range(num_trials):
            # --- Golay estimation ---
            y_a    = transmit(a, h_true, snr_db)
            y_b    = transmit(b, h_true, snr_db)
            h_est  = estimate_channel_golay(y_a, y_b, a, b, num_taps)
            err_golay_list.append(np.mean(np.abs(h_est - h_true.real) ** 2))

            # --- LS estimation with random BPSK pilot ---
            pilot  = rng_pilot.choice([-1.0, 1.0], size=N)
            y_p    = transmit(pilot, h_true, snr_db)
            h_ls   = estimate_channel_ls(y_p, pilot, num_taps)
            err_ls_list.append(np.mean(np.abs(h_ls - h_true.real) ** 2))

        mse_golay[i] = np.mean(err_golay_list)
        mse_ls[i]    = np.mean(err_ls_list)

    return snr_range_db, mse_golay, mse_ls, h_true


#  6. PLOT EVERYTHING


def plot_channel_estimation(n=5, num_taps=5, demo_snr_db=20):
    """
    Produce all 3 channel estimation plots:
      Plot 1 — True channel impulse response (magnitude + phase)
      Plot 2 — True vs Golay-estimated vs LS-estimated (at demo_snr_db)
      Plot 3 — MSE vs SNR: Golay vs LS random pilot
    """

    print("Running MSE vs SNR experiment (this takes ~15 seconds) ...")
    snr_range, mse_golay, mse_ls, h_true = mse_vs_snr(n=n, num_taps=num_taps)

    a, b = golay_pair(n)
    N    = len(a)

    # Single-shot estimates at demo_snr_db for visual comparison
    y_a_demo = transmit(a, h_true, demo_snr_db)
    y_b_demo = transmit(b, h_true, demo_snr_db)
    h_golay_demo = estimate_channel_golay(y_a_demo, y_b_demo, a, b, num_taps)

    rng = np.random.default_rng(seed=55)
    pilot_demo = rng.choice([-1.0, 1.0], size=N)
    y_p_demo   = transmit(pilot_demo, h_true, demo_snr_db)
    h_ls_demo  = estimate_channel_ls(y_p_demo, pilot_demo, num_taps)

    print(f"  Demo SNR = {demo_snr_db} dB")
    print(f"  Golay MSE  = {np.mean(np.abs(h_golay_demo - h_true.real)**2):.6f}")
    print(f"  LS    MSE  = {np.mean(np.abs(h_ls_demo    - h_true.real)**2):.6f}")

    # ── colours ──────────────────────────────────────────────────────
    BLUE   = '#2563EB'
    GREEN  = '#059669'
    ORANGE = '#D97706'
    RED    = '#DC2626'
    PURPLE = '#7C3AED'
    GRAY   = '#9CA3AF'

    tap_idx = np.arange(num_taps)

    fig = plt.figure(figsize=(15, 12))
    fig.suptitle(
        f'Channel Estimation Using Golay Complementary Sequences  '
        f'(N={N}, {num_taps} taps)',
        fontsize=14, fontweight='bold', y=0.98
    )
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.50, wspace=0.35)

    # ── Plot 1a: True channel magnitude ──────────────────────────────
    ax1 = fig.add_subplot(gs[0, 0])
    ml, sl, bl = ax1.stem(tap_idx, np.abs(h_true), linefmt=BLUE,
                           markerfmt='o', basefmt='k-')
    plt.setp(sl, linewidth=2.0)
    plt.setp(ml, markersize=8, color=BLUE)
    ax1.set_title('True channel — impulse response (magnitude)', fontweight='bold')
    ax1.set_xlabel('Tap index')
    ax1.set_ylabel('|h[n]|')
    ax1.set_xticks(tap_idx)
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(bottom=0)
    for i, v in enumerate(np.abs(h_true)):
        ax1.annotate(f'{v:.3f}', (i, v), textcoords='offset points',
                     xytext=(0, 8), ha='center', fontsize=8, color=BLUE)

    # ── Plot 1b: True channel phase ───────────────────────────────────
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.bar(tap_idx, np.angle(h_true, deg=True), color=PURPLE, alpha=0.7,
            edgecolor='white', linewidth=0.5)
    ax2.set_title('True channel — phase per tap (degrees)', fontweight='bold')
    ax2.set_xlabel('Tap index')
    ax2.set_ylabel('Phase (deg)')
    ax2.set_xticks(tap_idx)
    ax2.axhline(0, color='black', linewidth=0.8)
    ax2.grid(True, alpha=0.3)

    # ── Plot 2: True vs estimated (Golay + LS) ────────────────────────
    ax3 = fig.add_subplot(gs[1, 0])
    width = 0.28
    x = np.arange(num_taps)
    ax3.bar(x - width,   np.abs(h_true),        width, label='True',        color=BLUE,   alpha=0.85)
    ax3.bar(x,           np.abs(h_golay_demo),  width, label='Golay est.',  color=GREEN,  alpha=0.85)
    ax3.bar(x + width,   np.abs(h_ls_demo),     width, label='LS est.',     color=ORANGE, alpha=0.85)
    ax3.set_title(f'True vs estimated channel  (SNR = {demo_snr_db} dB)',
                  fontweight='bold')
    ax3.set_xlabel('Tap index')
    ax3.set_ylabel('Magnitude')
    ax3.set_xticks(x)
    ax3.legend(fontsize=9)
    ax3.grid(True, alpha=0.3, axis='y')
    ax3.set_ylim(bottom=0)

    # ── Plot 3: MSE vs SNR ────────────────────────────────────────────
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.semilogy(snr_range, mse_golay, color=GREEN,  linewidth=2.5,
                 marker='o', markersize=5, label='Golay estimator')
    ax4.semilogy(snr_range, mse_ls,    color=ORANGE, linewidth=2.5,
                 marker='s', markersize=5, linestyle='--', label='LS (random pilot)')

    # Mark the demo SNR point
    idx_demo = np.argmin(np.abs(snr_range - demo_snr_db))
    ax4.axvline(demo_snr_db, color=GRAY, linewidth=1.2, linestyle=':',
                label=f'Demo SNR = {demo_snr_db} dB')
    ax4.scatter([demo_snr_db], [mse_golay[idx_demo]], color=GREEN,  zorder=5, s=80)
    ax4.scatter([demo_snr_db], [mse_ls[idx_demo]],    color=ORANGE, zorder=5, s=80)

    ax4.set_title('MSE vs SNR  —  KEY RESULT', fontweight='bold')
    ax4.set_xlabel('SNR (dB)')
    ax4.set_ylabel('Mean Square Error (MSE)')
    ax4.legend(fontsize=9)
    ax4.grid(True, alpha=0.3, which='both')
    ax4.set_xlim(snr_range[0] - 1, snr_range[-1] + 1)

    plt.show()
    print("\nAll plots displayed.")



#  RUN


plot_channel_estimation(
    n          = 5,          # sequence length = 2^5 = 32
    num_taps   = 5,          # 5-tap multipath channel
    demo_snr_db= 20          # SNR for the visual comparison plot
)