# -*- coding: utf-8 -*-
"""golay pairs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChHjA7GU44wVua3-3rhNbzXLdZVi__62
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

#  1. GOLAY PAIR GENERATOR

def golay_pair(n):
    """
    Generate a Golay complementary pair (a, b) of length 2^n
    using the recursive Golay-Rudin-Shapiro construction.

    Base case (n=0): a = [1], b = [1]
    Recursion:
        a_new = concatenate(a,  b)
        b_new = concatenate(a, -b)
    """
    if n == 0:
        return np.array([1.0]), np.array([1.0])

    a_prev, b_prev = golay_pair(n - 1)

    a_new = np.concatenate([a_prev,  b_prev])
    b_new = np.concatenate([a_prev, -b_prev])

    return a_new, b_new

#  2. VERIFY THE COMPLEMENTARY PROPERTY

def verify_golay(a, b):
    """
    Verify: autocorr(a) + autocorr(b) = 2N * delta
    Returns True if the property holds (within floating-point tolerance).
    """
    N = len(a)

    # Full correlation (2N-1 points), zero-lag is at index N-1
    corr_a = np.correlate(a, a, mode='full')
    corr_b = np.correlate(b, b, mode='full')
    combined = corr_a + corr_b

    # Expected: 2N at zero-lag, 0 everywhere else
    expected = np.zeros(2 * N - 1)
    expected[N - 1] = 2 * N

    return np.allclose(combined, expected, atol=1e-10), corr_a, corr_b, combined

#  3. PLOT EVERYTHING

def plot_sequences(n=4):
    a, b = golay_pair(n)
    N = len(a)
    passed, corr_a, corr_b, combined = verify_golay(a, b)

    lags = np.arange(-(N - 1), N)

    fig = plt.figure(figsize=(14, 10))
    fig.suptitle(f'Golay Complementary Pair  |  Length = {N}  (n={n})',
                 fontsize=14, fontweight='bold', y=0.98)

    gs = gridspec.GridSpec(3, 2, figure=fig, hspace=0.55, wspace=0.35)

    BLUE   = '#2563EB'
    GREEN  = '#059669'
    ORANGE = '#D97706'
    RED    = '#DC2626'
    PURPLE = '#7C3AED'

    # --- Plot 1: Sequence a ---
    ax1 = fig.add_subplot(gs[0, 0])
    markerline, stemlines, baseline = ax1.stem(range(N), a, linefmt=BLUE,
                                                markerfmt='o', basefmt='k-')
    plt.setp(stemlines, linewidth=1.5)
    plt.setp(markerline, markersize=6, color=BLUE)
    ax1.set_title('Sequence  a', fontweight='bold')
    ax1.set_xlabel('Index')
    ax1.set_ylabel('Amplitude')
    ax1.set_ylim(-1.5, 1.5)
    ax1.set_yticks([-1, 0, 1])
    ax1.grid(True, alpha=0.3)
    ax1.axhline(0, color='black', linewidth=0.8)

    # --- Plot 2: Sequence b ---
    ax2 = fig.add_subplot(gs[0, 1])
    markerline, stemlines, baseline = ax2.stem(range(N), b, linefmt=GREEN,
                                                markerfmt='o', basefmt='k-')
    plt.setp(stemlines, linewidth=1.5)
    plt.setp(markerline, markersize=6, color=GREEN)
    ax2.set_title('Sequence  b', fontweight='bold')
    ax2.set_xlabel('Index')
    ax2.set_ylabel('Amplitude')
    ax2.set_ylim(-1.5, 1.5)
    ax2.set_yticks([-1, 0, 1])
    ax2.grid(True, alpha=0.3)
    ax2.axhline(0, color='black', linewidth=0.8)

    # --- Plot 3: Autocorrelation of a ---
    ax3 = fig.add_subplot(gs[1, 0])
    markerline, stemlines, baseline = ax3.stem(lags, corr_a, linefmt=BLUE,
                                                markerfmt='o', basefmt='k-')
    plt.setp(stemlines, linewidth=1.2)
    plt.setp(markerline, markersize=4, color=BLUE)
    ax3.set_title('Autocorrelation of  a', fontweight='bold')
    ax3.set_xlabel('Lag')
    ax3.set_ylabel('Value')
    ax3.grid(True, alpha=0.3)
    ax3.axhline(0, color='black', linewidth=0.8)

    # --- Plot 4: Autocorrelation of b ---
    ax4 = fig.add_subplot(gs[1, 1])
    markerline, stemlines, baseline = ax4.stem(lags, corr_b, linefmt=GREEN,
                                                markerfmt='o', basefmt='k-')
    plt.setp(stemlines, linewidth=1.2)
    plt.setp(markerline, markersize=4, color=GREEN)
    ax4.set_title('Autocorrelation of  b', fontweight='bold')
    ax4.set_xlabel('Lag')
    ax4.set_ylabel('Value')
    ax4.grid(True, alpha=0.3)
    ax4.axhline(0, color='black', linewidth=0.8)

    # --- Plot 5: Combined autocorrelation (the KEY result) ---
    ax5 = fig.add_subplot(gs[2, :])
    markerline, stemlines, baseline = ax5.stem(lags, combined, linefmt=PURPLE,
                                                markerfmt='o', basefmt='k-')
    plt.setp(stemlines, linewidth=1.5)
    plt.setp(markerline, markersize=6, color=PURPLE)

    # Mark the zero-lag spike
    ax5.annotate(f'Zero-lag = 2N = {2*N}',
                 xy=(0, 2 * N), xytext=(2, 2 * N * 0.75),
                 fontsize=10, color=RED,
                 arrowprops=dict(arrowstyle='->', color=RED, lw=1.5))

    status = 'PASSED' if passed else 'FAILED'
    color  = 'green'  if passed else 'red'
    ax5.set_title(f'Sum of autocorrelations:  autocorr(a) + autocorr(b)  →  Verification: {status}',
                  fontweight='bold', color=color)
    ax5.set_xlabel('Lag')
    ax5.set_ylabel('Value')
    ax5.grid(True, alpha=0.3)
    ax5.axhline(0, color='black', linewidth=0.8)

    print(f"[n={n}] Length={N}  Verification: {status}")
    plt.show()

#  4. TEST MULTIPLE LENGTHS

def test_all_lengths():
    print("=" * 45)
    print("  Golay pair verification — all lengths")
    print("=" * 45)
    for n in range(1, 8):
        a, b = golay_pair(n)
        passed, _, _, _ = verify_golay(a, b)
        status = "PASSED" if passed else "FAILED"
        print(f"  n={n}  length=2^{n}={len(a):>4}   [{status}]")
    print("=" * 45)

#  RUN

if __name__ == '__main__':
    test_all_lengths()
    plot_sequences(n=4)   # change n to get a different length