# -*- coding: utf-8 -*-
"""papr analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b48HRAj3SmAF4_R484Q58qikVAhnqKzf
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

#  1. GOLAY PAIR GENERATOR  (self-contained — no external import)

def golay_pair(n):
    """
    Generate a Golay complementary pair (a, b) of length 2^n.
    Recursive construction:
        base:      a=[1], b=[1]
        recursion: a_new = [a,  b]
                   b_new = [a, -b]
    """
    if n == 0:
        return np.array([1.0]), np.array([1.0])
    a_prev, b_prev = golay_pair(n - 1)
    return np.concatenate([a_prev,  b_prev]), \
           np.concatenate([a_prev, -b_prev])

#  2. OFDM MODULATOR

def ofdm_signal(subcarriers):
    N = len(subcarriers)
    return np.fft.ifft(subcarriers) * np.sqrt(N)

#  3. PAPR CALCULATOR

def compute_papr(signal):
    power = np.abs(signal) ** 2
    return 10 * np.log10(np.max(power) / np.mean(power))

#  4. CCDF CALCULATOR

def ccdf(papr_values, num_points=500):
    x = np.linspace(papr_values.min() - 0.5, papr_values.max() + 0.5, num_points)
    y = np.array([np.mean(papr_values > xi) for xi in x])
    return x, y

#  5. RUN EXPERIMENT

def run_papr_experiment(n=5, num_random_trials=5000):
    N = 2 ** n
    a, b = golay_pair(n)

    golay_sig_a = ofdm_signal(a)
    golay_sig_b = ofdm_signal(b)
    papr_ga = compute_papr(golay_sig_a)
    papr_gb = compute_papr(golay_sig_b)

    print(f"\n{'='*50}")
    print(f"  PAPR Analysis  |  N={N} subcarriers  (n={n})")
    print(f"{'='*50}")
    print(f"  Golay sequence a   PAPR = {papr_ga:.3f} dB")
    print(f"  Golay sequence b   PAPR = {papr_gb:.3f} dB")
    print(f"  Theoretical bound        <= 3.010 dB")

    rng = np.random.default_rng(seed=42)
    papr_random = np.array([
        compute_papr(ofdm_signal(rng.choice([-1.0, 1.0], size=N)))
        for _ in range(num_random_trials)
    ])

    print(f"\n  Random BPSK OFDM ({num_random_trials} trials)")
    print(f"    Mean PAPR = {papr_random.mean():.2f} dB")
    print(f"    Max  PAPR = {papr_random.max():.2f} dB")
    print(f"{'='*50}")

    return golay_sig_a, golay_sig_b, papr_ga, papr_gb, papr_random



#  6. PLOT EVERYTHING


def plot_papr(n=5, num_random_trials=5000):

    golay_sig_a, golay_sig_b, papr_ga, papr_gb, papr_random = \
        run_papr_experiment(n, num_random_trials)

    N = 2 ** n
    BLUE   = '#2563EB'
    GREEN  = '#059669'
    ORANGE = '#D97706'
    RED    = '#DC2626'

    fig = plt.figure(figsize=(14, 11))
    fig.suptitle(
        f'PAPR Analysis — Golay OFDM vs Random BPSK OFDM  (N={N} subcarriers)',
        fontsize=14, fontweight='bold', y=0.98
    )
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.32)
    time_axis = np.arange(N)

    # ── Plot 1: Golay time-domain magnitude ──
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.plot(time_axis, np.abs(golay_sig_a), color=BLUE,
             linewidth=1.8, label='Sequence a')
    ax1.plot(time_axis, np.abs(golay_sig_b), color=GREEN,
             linewidth=1.8, linestyle='--', label='Sequence b')
    ax1.set_title('Golay OFDM — time-domain magnitude', fontweight='bold')
    ax1.set_xlabel('Sample index')
    ax1.set_ylabel('|x[n]|')
    ax1.legend(fontsize=9)
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(bottom=0)

    # ── Plot 2: Random OFDM time-domain magnitude ──
    rng2 = np.random.default_rng(seed=7)
    rand_sig = ofdm_signal(rng2.choice([-1.0, 1.0], size=N))

    ax2 = fig.add_subplot(gs[0, 1])
    ax2.plot(time_axis, np.abs(rand_sig), color=ORANGE, linewidth=1.8)
    ax2.set_title('Random BPSK OFDM — time-domain magnitude', fontweight='bold')
    ax2.set_xlabel('Sample index')
    ax2.set_ylabel('|x[n]|')
    ax2.grid(True, alpha=0.3)
    ax2.set_ylim(bottom=0)

    # ── Plot 3: PAPR histogram ──
    ax3 = fig.add_subplot(gs[1, 0])
    ax3.hist(papr_random, bins=60, color=ORANGE, alpha=0.75,
             edgecolor='white', linewidth=0.4, label='Random BPSK')
    ax3.axvline(papr_ga, color=BLUE,  linewidth=2.5,
                label=f'Golay a  ({papr_ga:.2f} dB)')
    ax3.axvline(papr_gb, color=GREEN, linewidth=2.5, linestyle='--',
                label=f'Golay b  ({papr_gb:.2f} dB)')
    ax3.axvline(3.01,    color=RED,   linewidth=1.5, linestyle=':',
                label='3 dB bound')
    ax3.set_title('PAPR distribution — random BPSK OFDM', fontweight='bold')
    ax3.set_xlabel('PAPR (dB)')
    ax3.set_ylabel('Count')
    ax3.legend(fontsize=8.5)
    ax3.grid(True, alpha=0.3)

    # ── Plot 4: CCDF — key result ──
    ax4 = fig.add_subplot(gs[1, 1])
    x_rand, y_rand = ccdf(papr_random)
    ax4.semilogy(x_rand, np.clip(y_rand, 1e-5, 1),
                 color=ORANGE, linewidth=2.2, label='Random BPSK OFDM')
    ax4.axvline(papr_ga, color=BLUE,  linewidth=2.5,
                label=f'Golay a  ({papr_ga:.2f} dB)')
    ax4.axvline(papr_gb, color=GREEN, linewidth=2.5, linestyle='--',
                label=f'Golay b  ({papr_gb:.2f} dB)')
    ax4.axvline(3.01,    color=RED,   linewidth=1.5, linestyle=':',
                label='3 dB theoretical bound')
    ax4.set_title('CCDF of PAPR  —  KEY RESULT', fontweight='bold')
    ax4.set_xlabel('PAPR threshold (dB)')
    ax4.set_ylabel('Pr(PAPR > threshold)')
    ax4.legend(fontsize=8.5)
    ax4.grid(True, alpha=0.3, which='both')
    ax4.set_xlim(left=0)
    ax4.set_ylim(1e-4, 1.2)

    plt.show()

#  RUN

plot_papr(n=5, num_random_trials=5000)